package com.parsomash.remote.compose.document

import android.annotation.SuppressLint
import androidx.compose.remote.creation.compose.capture.RememberRemoteDocumentInline
import androidx.compose.remote.creation.compose.layout.RemoteComposable
import androidx.compose.remote.player.core.RemoteDocument
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue

/**
 * Interface for generating Remote Compose documents using androidx.compose.remote.creation APIs
 */
interface DocumentGenerator {
    /**
     * Generates and saves a Remote Compose document from the provided content
     *
     * @param documentId Unique identifier for the document
     * @param content Composable content to be converted to a Remote Document
     * @param onDocumentGenerated Callback invoked when document generation is complete
     */
    @Composable
    @SuppressLint("RestrictedApi")
    fun GenerateAndSaveDocument(
        documentId: String,
        content: @Composable () -> Unit,
        onDocumentGenerated: (RemoteDocument, ByteArray) -> Unit
    )

    /**
     * Saves document bytes to storage
     *
     * @param documentId Unique identifier for the document
     * @param bytes Document bytes extracted using doc.buffer.buffer.cloneBytes()
     */
    suspend fun saveDocumentBytes(documentId: String, bytes: ByteArray)
}

/**
 * Implementation of DocumentGenerator using androidx.compose.remote.creation APIs
 *
 * This class uses RememberRemoteDocumentInline to generate Remote Compose documents
 * and extracts bytes using doc.buffer.buffer.cloneBytes() as specified in the requirements.
 */
class DocumentGeneratorImpl(
    private val fileSystemManager: FileSystemManager
) : DocumentGenerator {

    @SuppressLint("RestrictedApi")
    @Composable
    @Suppress("RestrictedApiAndroidX", "COMPOSE_APPLIER_CALL_MISMATCH")
    override fun GenerateAndSaveDocument(
        documentId: String,
        content: @RemoteComposable @Composable () -> Unit,
        onDocumentGenerated: (RemoteDocument, ByteArray) -> Unit
    ) {
        var documentGenerated by remember(documentId) { mutableStateOf(false) }

        // Use RememberRemoteDocumentInline to generate the Remote Document
        RememberRemoteDocumentInline(
            onDocument = { doc ->
                if (!documentGenerated) {
                    // Extract bytes using doc.buffer.buffer.cloneBytes() as specified
                    val documentBytes = doc.buffer.buffer.cloneBytes()
                    val remoteDocument = RemoteDocument(documentBytes)

                    // Mark as generated to prevent duplicate processing
                    documentGenerated = true

                    // Notify callback
                    onDocumentGenerated(remoteDocument, documentBytes)
                }
            }
        ) {
            // Render the provided content within the Remote Compose context
            content()
        }
    }

    override suspend fun saveDocumentBytes(documentId: String, bytes: ByteArray) {
        fileSystemManager.saveDocument(documentId, bytes)
    }
}
